<?php

namespace Ifacesoft\Ice\Core\Infrastructure\Core;

abstract class Stream extends Service
{
    const FD = 'php://fd';
    const MEMORY = 'php://memory';
    const TEMP = 'php://temp';
    const FILTER = 'php://filter';

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    private function getStream()
    {
        return fopen($this->getParam('resource'), $this->getParam('mode'));
    }
}